version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: protocol
      POSTGRES_USER: cap
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django_network

  app:
    build: .
    container_name: app
    command: python myproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
