# Generated by Django 5.0.6 on 2024-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_name', models.CharField(default=False, max_length=20)),
                ('source_ip', models.CharField(default=False, max_length=20)),
                ('target_ip', models.CharField(default=False, max_length=20)),
                ('pattern', models.CharField(default='')),
            ],
        ),
    ]
