# Generated by Django 5.0.6 on 2024-06-08 15:58

import django.db.models.deletion
from django.db import migrations, models
from myapp.models import Protocol


def create_initial_data(apps, schema_editor):
    protocol = apps.get_model("myapp", "Protocol")
    protocols = [
        "TCP",
        "UDP",
        "ICMP",
        "HTTP",
        "FTP",
        "DNS",
        "SSH",
    ]
    for protocol in protocols:
        Protocol.objects.create(
            name=protocol,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
