# Generated by Django 5.0.4 on 2024-04-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_info', models.CharField(max_length=7, verbose_name='Pro_info')),
                ('Pro_len', models.IntegerField(verbose_name='Pro_len')),
            ],
        ),
    ]
