# Generated by Django 5.0.6 on 2024-06-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolinfo',
            old_name='protocol',
            new_name='protocol_id',
        ),
    ]
