# Generated by Django 5.0.4 on 2024-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolPacketCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
