# Generated by Django 5.0.4 on 2024-05-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_protocolpacketcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProtocolPacketCount',
        ),
    ]
