# Generated by Django 5.0.4 on 2024-05-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_protocolcount_protocol_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProtocolCount',
        ),
    ]
