# Generated by Django 5.0.4 on 2024-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_protocolcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=100, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='Pro_info',
            new_name='pro_info',
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='Pro_len',
            new_name='pro_len',
        ),
    ]
