# Generated by Django 5.0.4 on 2024-06-03 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Protocol',
        ),
        migrations.DeleteModel(
            name='ProtocolCount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='src',
            field=models.CharField(default='unknown', max_length=15, validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
