# Generated by Django 5.0.4 on 2024-06-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_packet_protocolinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
