# Generated by Django 5.0.4 on 2024-06-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_name_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='protocol_name',
        ),
    ]
