# Generated by Django 5.0.4 on 2024-06-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_type_item_protocol_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packet',
        ),
        migrations.RemoveField(
            model_name='item',
            name='src',
        ),
        migrations.AddField(
            model_name='item',
            name='dest_IP',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='src_IP',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
