# Generated by Django 5.0.4 on 2024-06-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_packet_remove_item_src_item_dest_ip_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='protocolinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='protocolinfo',
            name='src',
        ),
        migrations.AddField(
            model_name='protocolinfo',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='protocolinfo',
            name='dest_IP',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='protocolinfo',
            name='protocol_name',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='protocolinfo',
            name='src_IP',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
